# Full Shiny Server configuration
# Replace /etc/shiny-server/shiny-server.conf with this file

run_as shiny;

sanitize_errors false;
preserve_logs true;

server {
  listen 3838;

  location / {
    site_dir /srv/shiny-server;
    log_dir /var/log/shiny-server;
    directory_index on;
  }

  location /richStudio {
     app_dir /home/juhur/shinyapps/richStudio;
     run_as juhur;
     log_dir /home/juhur/shinyapps/richStudio/logs;
     directory_index off;
     app_idle_timeout 43200;
  }

}
